app_id: "211ab428-80c4-47e5-ad65-727fdbd89207"
app_secret: "rwmyrH0081xuYICINR7#[-~"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read files.readwrite"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
